using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Time_Travel;

namespace DatabaseManagement
{
    class Program
    {
        static void Main(string[] args)
        {
            CountryData db = new CountryData(); //CountryDatabase

            using (db)
            {
                Country africa1 = new AfricanCountry("Nigeria", "Africa");
                Country africa2 = new AfricanCountry("Ethiopia", "Africa");
                Country africa3 = new AfricanCountry("Egypt", "Africa");
                Country africa4 = new AfricanCountry("Democratic Republic Of Congo", "Africa");
                Country africa5 = new AfricanCountry("Tanzania", "Africa");
                Country africa6 = new AfricanCountry("South Africa", "Africa");
                Country africa7 = new AfricanCountry("Kenya", "Africa");
                Country africa8 = new AfricanCountry("Uganda", "Africa");
                Country africa9 = new AfricanCountry("Algeria", "Africa");
                Country africa10 = new AfricanCountry("Sudan", "Africa");
                Country africa11 = new AfricanCountry("Morocco", "Africa");
                Country africa12 = new AfricanCountry("Angola", "Africa");
                Country africa13 = new AfricanCountry("Mozambique", "Africa");
                Country africa14 = new AfricanCountry("Ghana", "Africa");
                Country africa15 = new AfricanCountry("Madagascar", "Africa");
                Country africa16 = new AfricanCountry("Cameroon", "Africa");
                Country africa17 = new AfricanCountry("Côte d'Ivoire", "Africa");
                Country africa18 = new AfricanCountry("Niger", "Africa");
                Country africa19 = new AfricanCountry("Burkina Faso", "Africa");
                Country africa20 = new AfricanCountry("Mali", "Africa");
                Country africa21 = new AfricanCountry("Malawi", "Africa");
                Country africa22 = new AfricanCountry("Zambia", "Africa");
                Country africa23 = new AfricanCountry("Senegal", "Africa");
                Country africa24 = new AfricanCountry("Chad", "Africa");
                Country africa25 = new AfricanCountry("Somalia", "Africa");
                Country africa26 = new AfricanCountry("Zimbabwe", "Africa");
                Country africa27 = new AfricanCountry("Guinea", "Africa");
                Country africa28 = new AfricanCountry("Rwanda", "Africa");
                Country africa29 = new AfricanCountry("Benin", "Africa");
                Country africa30 = new AfricanCountry("Burundi", "Africa");
                Country africa31 = new AfricanCountry("Tunisia", "Africa");
                Country africa32 = new AfricanCountry("South Sudan", "Africa");
                Country africa33 = new AfricanCountry("Togo", "Africa");
                Country africa34 = new AfricanCountry("Sierra Leone", "Africa");
                Country africa35 = new AfricanCountry("Libya", "Africa");
                Country africa36 = new AfricanCountry("Congo", "Africa");
                Country africa37 = new AfricanCountry("Liberia", "Africa");
                Country africa38 = new AfricanCountry("Central African Republic", "Africa");
                Country africa39 = new AfricanCountry("Mauritania", "Africa");
                Country africa40 = new AfricanCountry("Eritrea", "Africa");
                Country africa41 = new AfricanCountry("Namibia", "Africa");
                Country africa42 = new AfricanCountry("Gambia", "Africa");
                Country africa43 = new AfricanCountry("Botswana", "Africa");
                Country africa44 = new AfricanCountry("Gabon", "Africa");
                Country africa45 = new AfricanCountry("Lesotho", "Africa");
                Country africa46 = new AfricanCountry("Guinea-Bissau", "Africa");
                Country africa47 = new AfricanCountry("Equatorial Guinea", "Africa");
                Country africa48 = new AfricanCountry("Mauritius", "Africa");
                Country africa49 = new AfricanCountry("Eswatini", "Africa");
                Country africa50 = new AfricanCountry("Djibouti", "Africa");
                Country africa51 = new AfricanCountry("Comoros", "Africa");
                Country africa52 = new AfricanCountry("Cabo Verde", "Africa");
                Country africa53 = new AfricanCountry("Sao Tom & Principe", "Africa");
                Country africa54 = new AfricanCountry("Seychelles", "Africa");
                //Asian Region
                Country asia1 = new AsianCountry("China", "Asia");
                Country asia2 = new AsianCountry("India", "Asia");
                Country asia3 = new AsianCountry("Indonesia", "Asia");
                Country asia4 = new AsianCountry("Pakistan", "Asia");
                Country asia5 = new AsianCountry("Bangladesh", "Asia");
                Country asia6 = new AsianCountry("Japan", "Asia");
                Country asia7 = new AsianCountry("Philippines", "Asia");
                Country asia8 = new AsianCountry("Vietnam", "Asia");
                Country asia9 = new AsianCountry("Turkey", "Asia");
                Country asia10 = new AsianCountry("Iran", "Asia");
                Country asia11 = new AsianCountry("Thailand", "Asia");
                Country asia12 = new AsianCountry("Myanmar", "Asia");
                Country asia13 = new AsianCountry("South Korea", "Asia");
                Country asia14 = new AsianCountry("Iraq", "Asia");
                Country asia15 = new AsianCountry("Afghanistan", "Asia");
                Country asia16 = new AsianCountry("Saudi Arabia", "Asia");
                Country asia17 = new AsianCountry("Uzbekistan", "Asia");
                Country asia18 = new AsianCountry("Malaysia", "Asia");
                Country asia19 = new AsianCountry("Yemen", "Asia");
                Country asia20 = new AsianCountry("Nepal", "Asia");
                Country asia21 = new AsianCountry("North Korea", "Asia");
                Country asia22 = new AsianCountry("Sri Lanka", "Asia");
                Country asia23 = new AsianCountry("Kazakhstan", "Asia");
                Country asia24 = new AsianCountry("Syria", "Asia");
                Country asia25 = new AsianCountry("Cambodia", "Asia");
                Country asia26 = new AsianCountry("Jordan", "Asia");
                Country asia27 = new AsianCountry("Azerbaijan", "Asia");
                Country asia28 = new AsianCountry("United Arab Emirates", "Asia");
                Country asia29 = new AsianCountry("Tajikistan", "Asia");
                Country asia30 = new AsianCountry("Israel", "Asia");
                Country asia31 = new AsianCountry("Laos", "Asia");
                Country asia32 = new AsianCountry("Lebanon", "Asia");
                Country asia33 = new AsianCountry("Kyrgyzstan", "Asia");
                Country asia34 = new AsianCountry("Turkmenistan", "Asia");
                Country asia35 = new AsianCountry("Singapore", "Asia");
                Country asia36 = new AsianCountry("Oman", "Asia");
                Country asia37 = new AsianCountry("State of Palestine", "Asia");
                Country asia38 = new AsianCountry("Kuwait", "Asia");
                Country asia39 = new AsianCountry("Georgia", "Asia");
                Country asia40 = new AsianCountry("Mongolia", "Asia");
                Country asia41 = new AsianCountry("Armenia", "Asia");
                Country asia42 = new AsianCountry("Qatar", "Asia");
                Country asia43 = new AsianCountry("Bahrain", "Asia");
                Country asia44 = new AsianCountry("Timor-Leste", "Asia");
                Country asia45 = new AsianCountry("Cyprus", "Asia");
                Country asia46 = new AsianCountry("Bhutan", "Asia");
                Country asia47 = new AsianCountry("Maldives", "Asia");
                Country asia48 = new AsianCountry("Brunei", "Asia");
                //European Region
                Country euro1 = new Country("Russia", "Europe");
                Country euro2 = new EuropeanCountry("Germany", "Europe");
                Country euro3 = new EuropeanCountry("United Kingdom", "Europe");
                Country euro4 = new EuropeanCountry("France", "Europe");
                Country euro5 = new EuropeanCountry("Italy", "Europe");
                Country euro6 = new EuropeanCountry("Spain", "Europe");
                Country euro7 = new EuropeanCountry("Ukraine", "Europe");
                Country euro8 = new EuropeanCountry("Poland", "Europe");
                Country euro9 = new EuropeanCountry("Romania", "Europe");
                Country euro10 = new EuropeanCountry("Netherlands", "Europe");
                Country euro11 = new EuropeanCountry("Belgium", "Europe");
                Country euro12 = new EuropeanCountry("Czech Republic", "Europe");
                Country euro13 = new EuropeanCountry("Greece", "Europe");
                Country euro14 = new EuropeanCountry("Portugal", "Europe");
                Country euro15 = new EuropeanCountry("Sweden", "Europe");
                Country euro16 = new EuropeanCountry("Hungary", "Europe");
                Country euro17 = new EuropeanCountry("Belarus", "Europe");
                Country euro18 = new EuropeanCountry("Austria", "Europe");
                Country euro19 = new EuropeanCountry("Serbia", "Europe");
                Country euro20 = new EuropeanCountry("Switzerland", "Europe");
                Country euro21 = new EuropeanCountry("Bulgaria", "Europe");
                Country euro22 = new EuropeanCountry("Denmark", "Europe");
                Country euro23 = new EuropeanCountry("Finland", "Europe");
                Country euro24 = new EuropeanCountry("Slovakia", "Europe");
                Country euro25 = new EuropeanCountry("Norway", "Europe");
                Country euro26 = new EuropeanCountry("Ireland", "Europe");
                Country euro27 = new EuropeanCountry("Croatia", "Europe");
                Country euro28 = new EuropeanCountry("Moldova", "Europe");
                Country euro29 = new EuropeanCountry("Bosnia and Herzegovina", "Europe");
                Country euro30 = new EuropeanCountry("Albania", "Europe");
                Country euro31 = new EuropeanCountry("Lithuania", "Europe");
                Country euro32 = new EuropeanCountry("North Macedonia", "Europe");
                Country euro33 = new EuropeanCountry("Slovenia", "Europe");
                Country euro34 = new EuropeanCountry("Latvia", "Europe");
                Country euro35 = new EuropeanCountry("Estonia", "Europe");
                Country euro36 = new EuropeanCountry("Montenegro", "Europe");
                Country euro37 = new EuropeanCountry("Luxembourg", "Europe");
                Country euro38 = new EuropeanCountry("Malta", "Europe");
                Country euro39 = new EuropeanCountry("Iceland", "Europe");
                Country euro40 = new EuropeanCountry("Andorra", "Europe");
                Country euro41 = new EuropeanCountry("Monaco", "Europe");
                Country euro42 = new EuropeanCountry("Liechtenstein", "Europe");
                Country euro43 = new EuropeanCountry("San Marino", "Europe");
                Country euro44 = new EuropeanCountry("Holy See", "Europe");
                //Latin American Region
                Country laac1 = new LatinCaribbeanCountry("Brazil", "Latin_America_and_Carribean");
                Country laac2 = new LatinCaribbeanCountry("Mexico", "Latin_America_and_Carribean");
                Country laac3 = new LatinCaribbeanCountry("Colombia", "Latin_America_and_Carribean");
                Country laac4 = new LatinCaribbeanCountry("Argentina", "Latin_America_and_Carribean");
                Country laac5 = new LatinCaribbeanCountry("Peru", "Latin_America_and_Carribean");
                Country laac6 = new LatinCaribbeanCountry("Venezuela", "Latin_America_and_Carribean");
                Country laac7 = new LatinCaribbeanCountry("Chile", "Latin_America_and_Carribean");
                Country laac8 = new LatinCaribbeanCountry("Guatemala", "Latin_America_and_Carribean");
                Country laac9 = new LatinCaribbeanCountry("Ecuador", "Latin_America_and_Carribean");
                Country laac10 = new LatinCaribbeanCountry("Bolivia", "Latin_America_and_Carribean");
                Country laac11 = new LatinCaribbeanCountry("Haiti", "Latin_America_and_Carribean");
                Country laac12 = new LatinCaribbeanCountry("Cuba", "Latin_America_and_Carribean");
                Country laac13 = new LatinCaribbeanCountry("Dominican Republic", "Latin_America_and_Carribean");
                Country laac14 = new LatinCaribbeanCountry("Honduras", "Latin_America_and_Carribean");
                Country laac15 = new LatinCaribbeanCountry("Paraguay", "Latin_America_and_Carribean");
                Country laac16 = new LatinCaribbeanCountry("Nicaragua", "Latin_America_and_Carribean");
                Country laac17 = new LatinCaribbeanCountry("El Salvador", "Latin_America_and_Carribean");
                Country laac18 = new LatinCaribbeanCountry("Costa Rica", "Latin_America_and_Carribean");
                Country laac19 = new LatinCaribbeanCountry("Panama", "Latin_America_and_Carribean");
                Country laac20 = new LatinCaribbeanCountry("Uruguay", "Latin_America_and_Carribean");
                Country laac21 = new LatinCaribbeanCountry("Jamaica", "Latin_America_and_Carribean");
                Country laac22 = new LatinCaribbeanCountry("Trinidad and Tobago", "Latin_America_and_Carribean");
                Country laac23 = new LatinCaribbeanCountry("Guyana", "Latin_America_and_Carribean");
                Country laac24 = new LatinCaribbeanCountry("Suriname", "Latin_America_and_Carribean");
                Country laac25 = new LatinCaribbeanCountry("Belize", "Latin_America_and_Carribean");
                Country laac26 = new LatinCaribbeanCountry("Bahamas", "Latin_America_and_Carribean");
                Country laac27 = new LatinCaribbeanCountry("Barbados", "Latin_America_and_Carribean");
                Country laac28 = new LatinCaribbeanCountry("Saint Lucia", "Latin_America_and_Carribean");
                Country laac29 = new LatinCaribbeanCountry("Grenada", "Latin_America_and_Carribean");
                Country laac30 = new LatinCaribbeanCountry("St. Vincent & Grenadines", "Latin_America_and_Carribean");
                Country laac31 = new LatinCaribbeanCountry("Antigua and Barbuda", "Latin_America_and_Carribean");
                Country laac32 = new LatinCaribbeanCountry("Dominica", "Latin_America_and_Carribean");
                Country laac33 = new LatinCaribbeanCountry("Saint Kitts & Nevis", "Latin_America_and_Carribean");
                //Oceanic Region
                Country oceania1 = new OceanicCountry("Australia", "Oceania");
                Country oceania2 = new OceanicCountry("Papua New Guinea", "Oceania");
                Country oceania3 = new OceanicCountry("New Zealand", "Oceania");
                Country oceania4 = new OceanicCountry("Fiji", "Oceania");
                Country oceania5 = new OceanicCountry("Solomon Islands", "Oceania");
                Country oceania6 = new OceanicCountry("Vanuatu", "Oceania");
                Country oceania7 = new OceanicCountry("Samoa", "Oceania");
                Country oceania8 = new OceanicCountry("Kiribati", "Oceania");
                Country oceania9 = new OceanicCountry("Micronesia", "Oceania");
                Country oceania10 = new OceanicCountry("Tonga", "Oceania");
                Country oceania11 = new OceanicCountry("Marshall Islands", "Oceania");
                Country oceania12 = new OceanicCountry("Palau", "Oceania");
                Country oceania13 = new OceanicCountry("Tuvalu", "Oceania");
                Country oceania14 = new OceanicCountry("Nauru", "Oceania");
                Country northa1 = new NorthAmericanCountry("United States", "North_America");
                Country northa2 = new NorthAmericanCountry("Canada", "North_America");
                db.WorldCountry.Add(africa1);
                db.WorldCountry.Add(africa2);
                db.WorldCountry.Add(africa3);
                db.WorldCountry.Add(africa4);
                db.WorldCountry.Add(africa5);
                db.WorldCountry.Add(africa6);
                db.WorldCountry.Add(africa7);
                db.WorldCountry.Add(africa8);
                db.WorldCountry.Add(africa9);
                db.WorldCountry.Add(africa10);
                db.WorldCountry.Add(africa11);
                db.WorldCountry.Add(africa12);
                db.WorldCountry.Add(africa13);
                db.WorldCountry.Add(africa14);
                db.WorldCountry.Add(africa15);
                db.WorldCountry.Add(africa16);
                db.WorldCountry.Add(africa17);
                db.WorldCountry.Add(africa18);
                db.WorldCountry.Add(africa19);
                db.WorldCountry.Add(africa20);
                db.WorldCountry.Add(africa21);
                db.WorldCountry.Add(africa22);
                db.WorldCountry.Add(africa23);
                db.WorldCountry.Add(africa24);
                db.WorldCountry.Add(africa25);
                db.WorldCountry.Add(africa26);
                db.WorldCountry.Add(africa27);
                db.WorldCountry.Add(africa28);
                db.WorldCountry.Add(africa29);
                db.WorldCountry.Add(africa30);
                db.WorldCountry.Add(africa31);
                db.WorldCountry.Add(africa32);
                db.WorldCountry.Add(africa33);
                db.WorldCountry.Add(africa34);
                db.WorldCountry.Add(africa35);
                db.WorldCountry.Add(africa36);
                db.WorldCountry.Add(africa37);
                db.WorldCountry.Add(africa38);
                db.WorldCountry.Add(africa39);
                db.WorldCountry.Add(africa40);
                db.WorldCountry.Add(africa41);
                db.WorldCountry.Add(africa42);
                db.WorldCountry.Add(africa43);
                db.WorldCountry.Add(africa44);
                db.WorldCountry.Add(africa45);
                db.WorldCountry.Add(africa46);
                db.WorldCountry.Add(africa47);
                db.WorldCountry.Add(africa48);
                db.WorldCountry.Add(africa49);
                db.WorldCountry.Add(africa50);
                db.WorldCountry.Add(africa51);
                db.WorldCountry.Add(africa52);
                db.WorldCountry.Add(africa53);
                db.WorldCountry.Add(africa54);
                db.WorldCountry.Add(asia1);
                db.WorldCountry.Add(asia2);
                db.WorldCountry.Add(asia3);
                db.WorldCountry.Add(asia4);
                db.WorldCountry.Add(asia5);
                db.WorldCountry.Add(asia6);
                db.WorldCountry.Add(asia7);
                db.WorldCountry.Add(asia8);
                db.WorldCountry.Add(asia9);
                db.WorldCountry.Add(asia10);
                db.WorldCountry.Add(asia11);
                db.WorldCountry.Add(asia12);
                db.WorldCountry.Add(asia13);
                db.WorldCountry.Add(asia14);
                db.WorldCountry.Add(asia15);
                db.WorldCountry.Add(asia16);
                db.WorldCountry.Add(asia17);
                db.WorldCountry.Add(asia18);
                db.WorldCountry.Add(asia19);
                db.WorldCountry.Add(asia20);
                db.WorldCountry.Add(asia21);
                db.WorldCountry.Add(asia22);
                db.WorldCountry.Add(asia23);
                db.WorldCountry.Add(asia24);
                db.WorldCountry.Add(asia25);
                db.WorldCountry.Add(asia26);
                db.WorldCountry.Add(asia27);
                db.WorldCountry.Add(asia28);
                db.WorldCountry.Add(asia29);
                db.WorldCountry.Add(asia30);
                db.WorldCountry.Add(asia31);
                db.WorldCountry.Add(asia32);
                db.WorldCountry.Add(asia33);
                db.WorldCountry.Add(asia34);
                db.WorldCountry.Add(asia35);
                db.WorldCountry.Add(asia36);
                db.WorldCountry.Add(asia37);
                db.WorldCountry.Add(asia38);
                db.WorldCountry.Add(asia39);
                db.WorldCountry.Add(asia40);
                db.WorldCountry.Add(asia41);
                db.WorldCountry.Add(asia42);
                db.WorldCountry.Add(asia43);
                db.WorldCountry.Add(asia44);
                db.WorldCountry.Add(asia45);
                db.WorldCountry.Add(asia46);
                db.WorldCountry.Add(asia47);
                db.WorldCountry.Add(asia48);
                db.WorldCountry.Add(euro1);
                db.WorldCountry.Add(euro2);
                db.WorldCountry.Add(euro3);
                db.WorldCountry.Add(euro4);
                db.WorldCountry.Add(euro5);
                db.WorldCountry.Add(euro6);
                db.WorldCountry.Add(euro7);
                db.WorldCountry.Add(euro8);
                db.WorldCountry.Add(euro9);
                db.WorldCountry.Add(euro10);
                db.WorldCountry.Add(euro11);
                db.WorldCountry.Add(euro12);
                db.WorldCountry.Add(euro13);
                db.WorldCountry.Add(euro14);
                db.WorldCountry.Add(euro15);
                db.WorldCountry.Add(euro16);
                db.WorldCountry.Add(euro17);
                db.WorldCountry.Add(euro18);
                db.WorldCountry.Add(euro19);
                db.WorldCountry.Add(euro20);
                db.WorldCountry.Add(euro21);
                db.WorldCountry.Add(euro22);
                db.WorldCountry.Add(euro23);
                db.WorldCountry.Add(euro24);
                db.WorldCountry.Add(euro25);
                db.WorldCountry.Add(euro26);
                db.WorldCountry.Add(euro27);
                db.WorldCountry.Add(euro28);
                db.WorldCountry.Add(euro29);
                db.WorldCountry.Add(euro30);
                db.WorldCountry.Add(euro31);
                db.WorldCountry.Add(euro32);
                db.WorldCountry.Add(euro33);
                db.WorldCountry.Add(euro34);
                db.WorldCountry.Add(euro35);
                db.WorldCountry.Add(euro36);
                db.WorldCountry.Add(euro37);
                db.WorldCountry.Add(euro38);
                db.WorldCountry.Add(euro39);
                db.WorldCountry.Add(euro40);
                db.WorldCountry.Add(euro41);
                db.WorldCountry.Add(euro42);
                db.WorldCountry.Add(euro43);
                db.WorldCountry.Add(euro44);
                db.WorldCountry.Add(laac1);
                db.WorldCountry.Add(laac2);
                db.WorldCountry.Add(laac3);
                db.WorldCountry.Add(laac4);
                db.WorldCountry.Add(laac5);
                db.WorldCountry.Add(laac6);
                db.WorldCountry.Add(laac7);
                db.WorldCountry.Add(laac8);
                db.WorldCountry.Add(laac9);
                db.WorldCountry.Add(laac10);
                db.WorldCountry.Add(laac11);
                db.WorldCountry.Add(laac12);
                db.WorldCountry.Add(laac13);
                db.WorldCountry.Add(laac14);
                db.WorldCountry.Add(laac15);
                db.WorldCountry.Add(laac16);
                db.WorldCountry.Add(laac17);
                db.WorldCountry.Add(laac18);
                db.WorldCountry.Add(laac19);
                db.WorldCountry.Add(laac20);
                db.WorldCountry.Add(laac21);
                db.WorldCountry.Add(laac22);
                db.WorldCountry.Add(laac23);
                db.WorldCountry.Add(laac24);
                db.WorldCountry.Add(laac25);
                db.WorldCountry.Add(laac26);
                db.WorldCountry.Add(laac27);
                db.WorldCountry.Add(laac28);
                db.WorldCountry.Add(laac29);
                db.WorldCountry.Add(laac30);
                db.WorldCountry.Add(laac31);
                db.WorldCountry.Add(laac32);
                db.WorldCountry.Add(laac33);
                db.WorldCountry.Add(oceania1);
                db.WorldCountry.Add(oceania2);
                db.WorldCountry.Add(oceania3);
                db.WorldCountry.Add(oceania4);
                db.WorldCountry.Add(oceania5);
                db.WorldCountry.Add(oceania6);
                db.WorldCountry.Add(oceania7);
                db.WorldCountry.Add(oceania8);
                db.WorldCountry.Add(oceania9);
                db.WorldCountry.Add(oceania10);
                db.WorldCountry.Add(oceania11);
                db.WorldCountry.Add(oceania12);
                db.WorldCountry.Add(oceania13);
                db.WorldCountry.Add(oceania14);
                db.WorldCountry.Add(northa1);
                db.WorldCountry.Add(northa2);
                Console.WriteLine("Countries added to database");
                db.SaveChanges();
                Console.WriteLine("Changes saved");
            }
        }
    }
}
